#!/bin/sh

./crawlelectiondata.php -y 2008 > ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 2004 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 2000 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1996 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1992 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1988 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1984 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1980 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1976 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1972 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1968 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1964 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1960 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1956 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1952 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1948 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1944 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1940 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1936 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1932 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1928 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1924 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1920 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1916 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1912 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1908 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1904 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1900 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1896 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1892 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1888 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1884 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1880 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1876 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1872 >> ../static/csv_examples/presidential_state.csv
./crawlelectiondata.php -y 1868 >> ../static/csv_examples/presidential_state.csv